#!usr/bin/env bash

# Install NGINX on server
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/.*listen\s*80.*/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo kill -s HUP $(cat /var/run/nginx.pid)
