#!/usr/bin/env bash
# Install NGINX on server

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo bash -c 'cat <<EOF >> /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>
EOF'

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
sudo service nginx restart
