#!/usr/bin/env bash
# Configure Nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" |sudo tee /var/www/html/index.html
var="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
cd /etc/nginx/sites-available/
sudo sed -i "s/server_name _;/$var/" default
cd -
sudo service nginx restart
