#!/usr/bin/env bash
# Configure Nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" |sudo tee /var/www/html/index.html
cat > /etc/nginx/sites-available/default << EOL
server {
	listen 80;
	server_name lagra.tech;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
EOL
sudo service nginx restart
