#!/usr/bin/env bash
#installing nginx and configuring response headers, 301 and 404 redirection

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx
var = $(hostname)
sudo bash -c 'cat <<EOF >> /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>
EOF'

sudo bash -c "cat <<EOF >> /var/www/html/error-404.html
<!DOCTYPE html>
<html>
<head>
    <title>Error 404 - Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>
EOF"
new_string="error_page 404 \/error-404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

sudo systemctl restart nginx
