#!/usr/bin/env bash
#installing nginx and configuring response headers, 301 and 404 redirection

supt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo bash -c 'cat <<EOF >> /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>
EOF'

sudo bash -c "cat <<EOF >> /var/www/html/error-404.html
<!DOCTYPE html>
<html>
<head>
    <title>Error 404 - Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>
EOF"

sudo bash -c "cat > /etc/nginx/sites-enabled/default << 'EOF'
server {
listen 80 default_server;
listen [::]:80 default_server;
server_tokens off;
root /var/www/html;
index index.html index.htm index.nginx-debian.html index.php;
server_name _;
location / {
    add_header X-Served-By \$hostname;
try_files \$uri \$uri/ =404;
}

location /redirect_me {
    return 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4';
}

error_page 404 /error-404.html;
location = /error-404.html {
    root /var/www/html;
    internal;
}
}
EOF"

sudo systemctl restart nginx 
