#!/usr/bin/env bash
# display best school 10 times with i in the 9th position using while loop

i=0
while [ $i -lt 10 ]; do
	echo "Best School"
	if [[ $i -eq 8 ]]; then
		echo "Hi"
	fi
    	((i++))
done
