#!/usr/bin/env bash
# display numbers with some bad lucks

i=1
while [ $i -le 20 ]; do
	echo "$i"
	case $i in
		4)
		    echo "bad luck in China"
		    ;;
		9)
		    echo "bad luck from Japan"
		    ;;
		17)
		    echo "bad luck from Italy"
		    ;;
	esac
    ((i++))
done
